# Rename application when deploying.
application: gf2-roba
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /packages/(.*)/(.*)
  static_files: app/packages/\1/\2
  upload: app/packages/(.*)/(.*)

- url: /out/packages/(.*)/(.*)
  static_files: app/packages/\1/\2
  upload: app/packages/(.*)/(.*)

- url: /a/.*
  script: main.app

- url: .*
  static_dir: app/web/out

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"

